name: Build and Deploy

on:
  push:
    branches:
      - deploy

env:
  REGISTRY: docker.io
  IMAGE_NAME: ssgwoo/ssgwoo-frontend
  VITE_API_URL: "https://api.ssgwoo.com"

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short SHA
        id: short_sha
        run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ steps.short_sha.outputs.short_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VITE_API_URL=${{ env.VITE_API_URL }}

  update-deployment:
    name: Update Deployment
    needs: build-and-push
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update deployment.yaml
        run: |
          # Get the short SHA of the current commit
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          
          # Update the image tag in deployment.yaml
          sed -i "s|image: .*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v$SHORT_SHA|" k8s/frontend-deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add k8s/
          git commit -m "🔄 Update deployment image to ${{ github.sha }}"
          git push